// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIia2CRA5V8-KubIVidotdooYSAxw43LE',
    appId: '1:465928965761:web:6db57709cef04093884780',
    messagingSenderId: '465928965761',
    projectId: 'qps-app-flutter',
    authDomain: 'qps-app-flutter.firebaseapp.com',
    storageBucket: 'qps-app-flutter.appspot.com',
    measurementId: 'G-NMRBWNF3PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Jn2RSSxtXKPWGCtLoiop20NL-b8j6nE',
    appId: '1:465928965761:android:9385034af6f4e4e9884780',
    messagingSenderId: '465928965761',
    projectId: 'qps-app-flutter',
    storageBucket: 'qps-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7CnOzRfXrhsq1BeAuniMheopzooJ-DM',
    appId: '1:465928965761:ios:48303d3d0673347f884780',
    messagingSenderId: '465928965761',
    projectId: 'qps-app-flutter',
    storageBucket: 'qps-app-flutter.appspot.com',
    iosClientId: '465928965761-cf9icudn7o2ajm48dpgd4oek1940cqfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalqps',
  );
}
